version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM modules
          command: |
            yarn
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Test
          command: |
            yarn test
      - save_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-and-test:
    jobs:
      - test

