version: 2.1
jobs:
  lint-testunit:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install NPM modules
          command: |
            yarn

      - run:
          name: Lint
          command: |
            yarn lint

      - run:
          name: Test
          command: |
            yarn test

      - run:
          name: Codecov
          command: |
            yarn codecov

      - save_cache:
          key: node-modules-{{ checksum ".circleci/config.yml" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
